CREATE OR REPLACE FUNCTION `proj.dataset.channel_group`(source STRING, medium STRING, name STRING, referrer STRING) AS (case
  when source = '' and regexp_contains(referrer, r'//([a-zA-Z0-9-.]+\.)?example\.com/') then 'Self'
  when source = '' and referrer = '' then 'Direct'
  when source = '' and regexp_contains(referrer, r'//(www\.google\.\w+(\.\w+)?|yandex\.ru)/$') then 'Organic Search'
  when source = '' and regexp_contains(referrer, r'//www\.google\.\w+(\.\w+)?/(url|search|m)\?') then 'Organic Search'
  when source = '' and regexp_contains(referrer, r'//(r\.)?search\.yahoo\.com/') then 'Organic Search'
  when source = '' and regexp_contains(referrer, r'//(sp-web\.)?search\.auone\.jp/') then 'Organic Search'
  when source = '' and regexp_contains(referrer, r'//(sp-)?search\.myjcom\.jp/') then 'Organic Search'
  when source = '' and regexp_contains(referrer, r'//([a-zA-Z0-9-.]+)?search\.(tb\.)?ask\.com/') then 'Organic Search'
  when source = '' and regexp_contains(referrer, r'//([a-zA-Z0-9-.]+\.)?jword\.jp/(search|clk)') then 'Organic Search'
  when source = '' and regexp_contains(referrer, r'//([a-zA-Z0-9-.]+\.)?(bing\.com|search\.goo\.ne\.jp|hao123\.com)/') then 'Organic Search'
  when source = '' and regexp_contains(referrer, r'//search\.(azby\.fmworld\.net|fenrir-inc\.com|fresheye\.com|gmx\.com|kinza\.jp|lilo\.org|livedoor\.com|nifty\.com|portal\.uqmobile\.jp|smt\.docomo\.ne\.jp|visymo\.com|yahoo\.co\.jp)/') then 'Organic Search'
  when source = '' and regexp_contains(referrer, r'//websearch\.(excite\.co\.jp|rakuten\.co\.jp)/') then 'Organic Search'
  when source = '' and referrer like '%//cgi.search.biglobe.ne.jp/%' then 'Organic Search'
  when source = '' and referrer like '%//duckduckgo.com/%' then 'Organic Search'
  when source = '' and referrer like '%//home.kingsoft.jp/%' then 'Organic Search'
  when source = '' and referrer like '%//int.search.myway.com/%' then 'Organic Search'
  when source = '' and referrer like '%//m.search.so-net.ne.jp/%' then 'Organic Search'
  when source = '' and referrer like '%//netlavis.azione.jp/%' then 'Organic Search'
  when source = '' and referrer like '%//www.ecosia.org/%' then 'Organic Search'
  when source = '' and referrer like '%//www.info.com/%' then 'Organic Search'
  when source = '' and referrer like '%//www.izito.jp/%' then 'Organic Search'
  when source = '' and referrer like '%//www.zapmeta.jp/%' then 'Organic Search'
  when source = '' and referrer like '%//ysearch.luna.tv/%' then 'Organic Search'
  when source = '' and referrer like '%//eonet.jp/search.html%' then 'Organic Search'
  when source = '' and referrer like '%//www.baidu.com/link?%' then 'Organic Search'
  when source = '' and referrer like '%//yandex.ru/clck/jsredir?%' then 'Organic Search'
  when source = '' and referrer like '%//www.so-net.ne.jp/search/%' then 'Organic Search'
  when source = '' and referrer like '%//t.co/%' then 'Social'
  when source = '' and referrer like '%//plus.url.google.com/%' then 'Social'
  when source = '' and regexp_contains(referrer, r'//([a-zA-Z0-9-.]+\.)?(twitter\.com|facebook\.com|line\.me|youtube\.com|instagram\.com|linkedin\.com|yammer\.com)/') then 'Social'
  when source = '' and regexp_contains(referrer, r'//([a-zA-Z0-9-.]+\.)?(pinterest|yelp)\.\w+(\.\w+)?/') then 'Social'
  when source != '' and regexp_contains(referrer, r'^(social|social-network|social-media|sm|social network|social media)$') then 'Social'
  when source != '' and medium = 'email' then 'Email'
  when source != '' and medium = 'affiliate' then 'Affiliate'
  --when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and regexp_contains(referrer, r'//(www\.google\.\w+(\.\w+)?|yandex\.ru)/$') then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and regexp_contains(referrer, r'//www\.google\.\w+(\.\w+)?/(url|search|m)\?') then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and regexp_contains(referrer, r'//(r\.)?search\.yahoo\.com/') then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and regexp_contains(referrer, r'//(sp-web\.)?search\.auone\.jp/') then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and regexp_contains(referrer, r'//(sp-)?search\.myjcom\.jp/') then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and regexp_contains(referrer, r'//([a-zA-Z0-9-.]+)?search\.(tb\.)?ask\.com/') then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and regexp_contains(referrer, r'//([a-zA-Z0-9-.]+\.)?jword\.jp/(search|clk)') then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and regexp_contains(referrer, r'//([a-zA-Z0-9-.]+\.)?(bing\.com|search\.goo\.ne\.jp|hao123\.com)/') then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and regexp_contains(referrer, r'//search\.(azby\.fmworld\.net|fenrir-inc\.com|fresheye\.com|gmx\.com|kinza\.jp|lilo\.org|livedoor\.com|nifty\.com|portal\.uqmobile\.jp|smt\.docomo\.ne\.jp|visymo\.com|yahoo\.co\.jp)/') then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and regexp_contains(referrer, r'//websearch\.(excite\.co\.jp|rakuten\.co\.jp)/') then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//cgi.search.biglobe.ne.jp/%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//duckduckgo.com/%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//home.kingsoft.jp/%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//int.search.myway.com/%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//m.search.so-net.ne.jp/%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//netlavis.azione.jp/%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//www.ecosia.org/%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//www.info.com/%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//www.izito.jp/%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//www.zapmeta.jp/%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//ysearch.luna.tv/%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//eonet.jp/search.html%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//www.baidu.com/link?%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//yandex.ru/clck/jsredir?%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer like '%//www.so-net.ne.jp/search/%' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') and referrer = 'http://www.ads.google.com/' then 'Paid Search'
  when source != '' and regexp_contains(medium, r'^(cpc|ppc|paidsearch)$') then 'Display'
  when source != '' and regexp_contains(medium, r'^(display|cpm|banner)$$') then 'Display'
  when source = '' and referrer like '%//googleads.g.doubleclick.net/%' then 'Display'
  when source != '' and regexp_contains(medium, r'^(cpv|cpa|cpp|content-text)$') then 'Other Advertising'
  when source = '' and referrer like 'android-app://%' then 'App'
  when source = '' and referrer != '' then 'Referral'
  else 'Other'
end);
